server:
  port: 8090

spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/sound-bind
    username: root
    password: yh172839
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: jwt-local

jwt:
  tokenType: "Bearer"
  accessTokenValidTime: 60000 #1분
  refreshTokenValidTime: 3600000 #1시간

---

spring:
  config:
    activate:
      on-profile: redis-local

redis:
  host: 127.0.0.1
  port: 6379

---

spring:
  config:
    activate:
      on-profile: mail-local
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        starttls:
          enable: true
        smtp:
          auth: true
          timeout: 20000

---