server:
  port: 8090

spring:
  application:
    name: auth-service
  cloud:
    config:
      name: auth-service
      profile: local
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: db-local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/sound-bind
    username: root
    password: yh172839
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: jwt-local
jwt:
  tokenType: "Bearer"
  accessTokenValidTime: 3600000 #1시간
  refreshTokenValidTime: 1209600000 #2주

---

spring:
  config:
    activate:
      on-profile: redis-local
redis:
  host: 127.0.0.1
  port: 6379