spring:
  config:
    activate:
      on-profile: oauth
    import: file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            scope:
              - account_email
              - profile_nickname
              - profile_image
            redirect-uri: ${OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - email
              - name
              - profile_image
            redirect-uri: ${OAUTH_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_NAME_ATTRIBUTE}
          naver:
            authorization-uri: ${NAVER_AUTHORIZATION_URI}
            token-uri: ${NAVER_TOKEN_URI}
            user-info-uri: ${NAVER_USER_INFO_URI}
            user-name-attribute: ${NAVER_NAME_ATTRIBUTE}

authorized-redirect-uris: ${AUTHORIZED_REDIRECT_URIS}