server:
  port: 8080

spring:
  cloud:
    config:
      name: auth-service
      profile: local
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/