server:
  port: 8040

spring:
  application:
    name: notification-service
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: ${MONGO_DB_URL}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /notification-service/v3/api-docs
  swagger-ui:
    path: /notification-service/swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: kafka-local
  kafka:
    bootstrap-servers: localhost:9090, localhost:9091, localhost:9092

---