server:
  port: 8040

spring:
  application:
    name: notification-service
  cloud:
    config:
      enabled: false
  config:
    import: file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /notification-service/v3/api-docs
  swagger-ui:
    path: /notification-service/swagger-ui.html