networks:
  soundbind-network:

services:
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    image: soundbind/config-server:latest
    container_name: soundbind-config-server
    ports:
      - 8888:8888
    environment:
      - spring.cloud.config.server.git.host-key=${CONFIG_SERVER_HOST_KEY}
      - spring.cloud.config.server.git.private-key=${CONFIG_SERVER_PRIVATE_KEY}
    restart: always
    networks:
      - soundbind-network

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    image: soundbind/eureka-server:latest
    container_name: soundbind-eureka-server
    ports:
      - 8761:8761
    environment:
      - server.port=8761
      - spring.cloud.config.name=eureka-server
      - spring.cloud.config.profile=dev
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
    depends_on:
      - config-server
    restart: always
    networks:
      - soundbind-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: soundbind/api-gateway:latest
    container_name: soundbind-api-gateway
    ports:
      - 8000:8000
    environment:
      - server.port=8000
      - spring.cloud.config.name=api-gateway
      - spring.cloud.config.profile=dev
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
    restart: always
    networks:
      - soundbind-network

  kafka-server:
    build:
      context: .
      dockerfile: kafka-server/Dockerfile
    image: soundbind/kafka-server:latest
    container_name: soundbind-kafka-server
    ports:
      - 9000:9000
    environment:
      - server.port=9000
      - spring.cloud.config.name=kafka-server
      - spring.cloud.config.profile=dev
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    restart: always
    networks:
      - soundbind-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    image: soundbind/auth-service:latest
    container_name: soundbind-auth-service
    ports:
      - 8090:8090
    environment:
      - server.port=8090
      - spring.cloud.config.name=auth-service
      - spring.cloud.config.profile=dev,kafka,jwt,oauth,redis,mail
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - kafka-server
      - mysql
      - redis
    restart: always
    networks:
      - soundbind-network

  music-service:
    build:
      context: .
      dockerfile: music-service/Dockerfile
    image: soundbind/music-service:latest
    container_name: soundbind-music-service
    ports:
      - 8070:8070
    environment:
      - server.port=8070
      - spring.cloud.config.name=music-service
      - spring.cloud.config.profile=dev,kafka,es,redis,file
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - kafka-server
      - mysql
      - redis
      - elasticsearch
    restart: always
    networks:
      - soundbind-network

  review-service:
    build:
      context: .
      dockerfile: review-service/Dockerfile
    image: soundbind/review-service:latest
    container_name: soundbind-review-service
    ports:
      - 8060:8060
    environment:
      - server.port=8060
      - spring.cloud.config.name=review-service
      - spring.cloud.config.profile=dev,kafka,es,redis
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - kafka-server
      - mysql
      - redis
      - elasticsearch
    restart: always
    networks:
      - soundbind-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    image: soundbind/notification-service:latest
    container_name: soundbind-notification-service
    ports:
      - 8040:8040
    environment:
      - server.port=8040
      - spring.cloud.config.name=notification-service
      - spring.cloud.config.profile=dev,kafka
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - kafka-server
      - mongodb
    restart: always
    networks:
      - soundbind-network

  pay-service:
    build:
      context: .
      dockerfile: pay-service/Dockerfile
    image: soundbind/pay-service:latest
    container_name: soundbind-pay-service
    ports:
      - 8050:8050
    environment:
      - server.port=8050
      - spring.cloud.config.name=pay-service
      - spring.cloud.config.profile=dev,kafka,es,redis
      - spring.config.import=configserver:http://config-server:8888
      - eureka.client.service-url.default-zone=http://eureka-server:8761
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - kafka-server
      - mysql
      - redis
      - elasticsearch
    restart: always
    networks:
      - soundbind-network

  mysql:
    image: mysql:latest
    container_name: soundbind-mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - soundbind-network

  mongodb:
    image: mongo:latest
    container_name: soundbind-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodb/data:/data/db
    restart: always
    networks:
      - soundbind-network

  redis:
    image: redis:latest
    container_name: soundbind-redis
    ports:
      - 6379:6379
    volumes:
      - ./db/redis/data:/data
      - ./db/redis/conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
    restart: always
    networks:
      - soundbind-network

  elasticsearch:
    image: elasticsearch:latest
    container_name: soundbind-elasticsearch
    ports:
      - 19200:9200
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./db/es/data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - soundbind-network

  zookeeper:
    image: zookeeper:latest
    ports:
      - 22181:2181
    restart: always
    networks:
      - soundbind-network

  kafka-1:
    image: kafka:latest
    ports:
      - 29091:9091
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    restart: always
    networks:
      - soundbind-network

  kafka-2:
    image: kafka:latest
    ports:
      - 29092:9092
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    restart: always
    networks:
      - soundbind-network

  kafka-3:
    image: kafka:latest
    ports:
      - 29093:9093
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    restart: always
    networks:
      - soundbind-network