version: '3.8'

networks:
  soundbind-network:

services:
  eureka-server:
    image: soundbind/eureka-server:latest
    container_name: soundbind-eureka-server
    ports:
      - "8761:8761"
    networks:
      - soundbind-network

  config-server:
    image: soundbind/config-server:latest
    container_name: soundbind-config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - soundbind-network

  api-gateway:
    image: soundbind/api-gateway:latest
    container_name: soundbind-api-gateway
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - CONFIG_NAME=api-gateway
      - CONFIG_PROFILE=prod
      - CONFIG_SERVER=http://config-server:8888
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka/
    depends_on:
      - config-server
    restart: on-failure
    networks:
      - soundbind-network

  kafka-server:
    image: soundbind/kafka-server:latest
    container_name: soundbind-kafka-server
    ports:
      - "9000:9000"
    environment:
      - SERVER_PORT=9000
      - CONFIG_NAME=kafka-server
      - CONFIG_PROFILE=prod
      - CONFIG_SERVER=http://config-server:8888
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
    restart: on-failure
    networks:
      - soundbind-network

  music-service:
    image: soundbind/music-service:latest
    container_name: soundbind-music-service
    ports:
      - "8070:8070"
    environment:
      - SERVER_PORT=8070
      - CONFIG_NAME=music-service
      - CONFIG_PROFILE=prod
      - CONFIG_SERVER=http://config-server:8888
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
      - api-gateway
      - kafka-server
      - mysql
    restart: on-failure
    networks:
      - soundbind-network

  mysql:
    image: soundbind/mysql:latest
    container_name: soundbind-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=yh172839
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - soundbind-network