version: '3'

networks:
  soundbind-network:

services:
  mysql:
    image: soundbind/mysql:latest
    container_name: soundbind-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=yh172839
    volumes:
      - ./data/mysql/:/var/lib/mysql
    networks:
      - soundbind-network

  config-server:
    image: soundbind/config-server:latest
    container_name: soundbind-config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://soundbind-config-server:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - soundbind-network

  eureka-server:
    image: soundbind/eureka-server:latest
    container_name: soundbind-eureka-server
    ports:
      - "8761:8761"
    environment:
      - spring.cloud.config.uri=http://soundbind-config-server:8888
      - spring.cloud.config.uri=eureka-server
      - spring.cloud.config.profile=prod
    depends_on:
      - config-server
    networks:
      - soundbind-network

  api-gateway:
    image: soundbind/api-gateway:latest
    container_name: soundbind-api-gateway
    ports:
      - "8000:8000"
    environment:
      - spring.cloud.config.uri=http://soundbind-config-server:8888
      - spring.cloud.config.uri=api-gateway
      - spring.cloud.config.profile=prod
    depends_on:
      - eureka-server
      - config-server
    networks:
      - soundbind-network

  kafka-server:
    image: soundbind/kafka-server:latest
    container_name: soundbind-kafka-server
    ports:
      - "9000:9000"
    environment:
      - spring.cloud.config.uri=http://soundbind-config-server:8888
      - spring.cloud.config.uri=kafka-server
      - spring.cloud.config.profile=prod
    depends_on:
      - eureka-server
      - config-server
    networks:
      - soundbind-network

  music-service:
    image: soundbind/music-service:latest
    container_name: soundbind-music-service
    ports:
      - "8070:8070"
    environment:
      - spring.cloud.config.uri=http://soundbind-config-server:8888
      - spring.cloud.config.uri=music-service
      - spring.cloud.config.profile=prod
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
      - kafka-server
      - mysql
    networks:
      - soundbind-network