server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-authorized
          uri: lb://AUTH-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/auth/**, /api/users/**
            - Method=DELETE,PUT,PATCH
        - id: auth-service-default
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**
            - Method=GET,POST
        - id: music-service
          uri: lb://MUSIC-SERVICE
          filters:
            - AuthorizationHeaderFilter
            - AuthenticationUserFilter
          predicates:
            - Path=/api/musics/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          filters:
            - AuthorizationHeaderFilter
            - AuthenticationUserFilter
          predicates:
            - Path=/api/reviews/**, /api/comments/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/notifications/**
        - id: kafka-server
          uri: lb://KAFKA-SERVER
          predicates:
            - Path=/api/kafka/**