server:
  port: ${SERVER_PORT}

spring:
  cloud:
    config:
      name: ${CONFIG_NAME}
      profile: ${CONFIG_PROFILE}
  config:
    import: configserver:${CONFIG_SERVER}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}