server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-authorized
          uri: lb://AUTH-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/auth/**, /api/users/**
            - Method=DELETE,PUT,PATCH
        - id: auth-service-default
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users/**
            - Method=GET,POST
        - id: music-service
          uri: lb://MUSIC-SERVICE
          filters:
            - AuthorizationHeaderFilter
            - AuthenticationUserFilter
          predicates:
            - Path=/api/musics/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          filters:
            - AuthorizationHeaderFilter
            - AuthenticationUserFilter
          predicates:
            - Path=/api/reviews/**, /api/comments/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/notifications/**
        - id: pay-service
          uri: lb://PAY-SERVICE
          filters:
            - AuthorizationHeaderFilter
            - AuthenticationUserFilter
          predicates:
            - Path=/api/payments/**, /api/sponsors/**
        - id: kafka-server
          uri: lb://KAFKA-SERVER
          predicates:
            - Path=/api/kafka/**
        - id: auth-service-swagger
          uri: http://localhost:8090
          predicates:
            - Path=/auth-service/v3/api-docs
            - Method=GET
        - id: music-service-swagger
          uri: http://localhost:8070
          predicates:
            - Path=/music-service/v3/api-docs
            - Method=GET
        - id: review-service-swagger
          uri: http://localhost:8060
          predicates:
            - Path=/review-service/v3/api-docs
            - Method=GET
        - id: notification-service-swagger
          uri: http://localhost:8040
          predicates:
            - Path=/notification-service/v3/api-docs
            - Method=GET
        - id: kafka-server-swagger
          uri: http://localhost:9000
          predicates:
            - Path=/kafka-server/v3/api-docs
            - Method=GET

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /auth-service/v3/api-docs
        name: Auth Service API
      - url: /music-service/v3/api-docs
        name: Music Service API
      - url: /review-service/v3/api-docs
        name: Review Service API
      - url: /notification-service/v3/api-docs
        name: Notification Service API
      - url: /kafka-server/v3/api-docs
        name: Kafka Server API