server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: kafka-server
          uri: lb://KAFKA-SERVER
          predicates:
            - Path=/api/kafka/**
        - id: auth-service-user
          uri: lb://AUTH-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/users
            - Method=DELETE
        - id: auth-service-default
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/users
        - id: music-service
          uri: lb://MUSIC-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/music/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          filters:
            - AuthorizationHeaderFilter
          predicates:
            - Path=/api/reviews/**, /api/comments/**