server:
  port: 9000

spring:
  application:
    name: kafka-server
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers:
      - http://localhost:9090
      - http://localhost:9091
      - http://localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/