server:
  port: 9000

spring:
  application:
    name: kafka-server
  cloud:
    config:
      enabled: false
  config:
    import: file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /kafka-server/v3/api-docs
  swagger-ui:
    path: /kafka-server/swagger-ui.html