server:
  port: 9000

spring:
  application:
    name: kafka-server
  cloud:
    config:
      enabled: false
  config:
    import: file:.env[.properties]
  r2dbc:
    url: ${POSTGRESQL_KAFKA_SERVER_DB_URL}
    username: ${POSTGRESQL_DB_USERNAME}
    password: ${POSTGRESQL_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

springdoc:
  api-docs:
    path: /kafka-server/v3/api-docs
  swagger-ui:
    path: /kafka-server/swagger-ui.html