server:
  port: 8060

spring:
  application:
    name: review-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${MYSQL_REVIEW_SERVICE_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: redis-local

redis:
  host: 127.0.0.1
  port: 6379

---