server:
  port: 8070

spring:
  application:
    name: music-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/sound-bind
    username: root
    password: yh172839
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  config:
    activate:
      on-profile: file-local
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  devtools:
    restart:
      enabled: false